### ISSUE TITLE
[DecoderPlugin] Empty headers + nyholm/psr7

### ISSUE THREAD

**Issue by jeromegamez** [php-http/client-common#102]
| Q            | A
| ------------ | ---
| Bug?         | I don't know :)
| New Feature? | no
| Version      | 1.7.0

#### Behavior

When using the DecoderPlugin, it is possible that `$newEncodings` in https://github.com/php-http/client-common/blob/master/src/Plugin/DecoderPlugin.php#L110 is an empty array - in the example below, this is the case when a Response has a `TransferEncoding` header and an empty body (`''`, not `null`).

When I use the plugin together with https://github.com/Nyholm/psr7 (/cc @Nyholm :)), that empty array causes an exception in https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L80.

I don't know if this is something that can/should be changed and if so, if it should be changed in the plugin or in nyholm/psr7 - on the one hand, guzzle/psr7 and zend/diactoros don't throw exceptions on empty headers, on the other hand, PSR-7 states that an exception should be thrown on invalid headers (https://github.com/php-fig/http-message/blob/master/src/MessageInterface.php#L130) - which again begs the question if an empty set of headers is to be considered invalid (oh, this is exhausting already 😅).

#### Steps to Reproduce

```bash
$ mkdir showcase && cd $_
$ composer require php-http/mock-client nyholm/psr7 
```

```php
<?php
// showcase.php
declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Http\Client\Common\Plugin\DecoderPlugin;
use Http\Client\Common\PluginClient;
use Http\Mock\Client as MockClient;
use Nyholm\Psr7\Factory\MessageFactory;

$messages = new MessageFactory();
$client = new MockClient($messages);
$pluginClient = new PluginClient($client, [
    new DecoderPlugin()
]);

$request = $messages->createRequest('GET', 'http://example.com');

$response = $messages->createResponse(200, 'OK', [
    'Transfer-Encoding' => ['chunked'],
], '');

$client->setDefaultResponse($response);

$pluginClient->sendRequest($request);
```

```bash
$ php showcase.php
PHP Fatal error:  Uncaught InvalidArgumentException: 
Header values must be non-empty strings in 
vendor/nyholm/psr7/src/MessageTrait.php:80
```

#### Possible Solutions

I see these possible solutions:

- In `DecoderPlugin::decodeOnEncodingHeader()`, if `$newEncodings` is empty, don't replace the header.
- In the same function, remove the header if `$newEncodings` is empty - I haven't looked it up, but I think when a header is empty, it is effectively removed with the guzzle/diactoros implementations.
- In nyholm/psr7, be less strict about empty headers. (The issue occurs with 0.3.0 and dev-master)

What do you think?

:octocat:

**Comment by Nyholm** [comment]
Sorry for the very late reply. I must have missed this issue. 

You are referring to version 0.3.0 of nyholm/psr7. There as been quite a few discussions about this topic. The result is a a new method for validating headers. 

```php
    /**
     * Make sure the header complies with RFC 7230.
     *
     * Header names must be a non-empty string consisting of token characters.
     *
     * Header values must be strings consisting of visible characters with all optional
     * leading and trailing whitespace stripped. This method will always strip such
     * optional whitespace. Note that the method does not allow folding whitespace within
     * the values as this was deprecated for almost all instances by the RFC.
     *
     * header-field = field-name ":" OWS field-value OWS
     * field-name   = 1*( "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^"
     *              / "_" / "`" / "|" / "~" / %x30-39 / ( %x41-5A / %x61-7A ) )
     * OWS          = *( SP / HTAB )
     * field-value  = *( ( %x21-7E / %x80-FF ) [ 1*( SP / HTAB ) ( %x21-7E / %x80-FF ) ] )
     *
     * @see https://tools.ietf.org/html/rfc7230#section-3.2.4
     */
    private function validateAndTrimHeader($header, $values): array
```

As you can see, empty header values are allowed. This is fixed in version 1.0 of nyholm/psr7. 

Thank you for reporting this.
