### ISSUE TITLE
Allo empty path

### ISSUE THREAD

**Issue by Neirda24** [php-http/client-common#106]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | Specific version or SHA of a commit

#### Actual Behavior

When setting the add_path it cannot be either `/` or empty.

#### Expected Behavior

Depending on which server I install the project I require to have a dynamic path prefix. Sometimes it will be empty sometimes not. I would need either to allow the empty or to allow `/` (as empty)

#### Possible Solutions

Remove this test https://github.com/php-http/client-common/blob/master/src/Plugin/AddPathPlugin.php#L33 and add a test if not empty here: https://github.com/php-http/client-common/blob/master/src/Plugin/AddPathPlugin.php#L49

**Comment by dbu** [comment]
could you make the whole plugin not be put in the chain if you don't need it? though i am unsure if you can, without duplicating the complete plugin configuration, which certainly would not be a nice solution either.

**Comment by Neirda24** [comment]
@dbu : exactly. I don't know any way to add this dynamically. the only solution I found was to use the `add_uri` with scheme, host, port and path. I would prefer to separate it.

**Comment by dbu** [comment]
i discussed with @sagikazarmark and we think your best solution is to write a wrapper plugin that instantiates the AddPathPlugin if its set up with a path, and otherwise just forwards the request without doing anything. 

allowing the path plugin to accept a no-op argument seems like an ugly solution. your use case is quite specific, so we would rather not add support and complexity into the library.

**Comment by Neirda24** [comment]
@dbu : I understand. however please reconsider if my need is really that specific... A lot of enterprises are setting up API managers. depending on their deployment environment they might have the same issue. Locally you rarely set up such complex architecture. but on production yes. It might be good to support such a thing.

I'll keep using the `set_uri` as I find it more readable than creating a whole new plugin for such a case. Thank you.

**Comment by dbu** [comment]
i am not saying you are the only one with that use case. but from the coding point of view, its weird to allow an empty path.

options we have:
- allow an empty path and make the plugin a noop
- have the DI extension skip the plugin when the path is empty

options the user has
- write a decorator plugin
- write a compiler pass that removes the plugin when its configured with e.g. a magical path that indicates it should not be used (yeah, that sounds hacky)

**Comment by joelwurtz** [comment]
Best solution is to duplicate and use yaml reference, for having different config, i think symfony yaml allow to use reference in yaml, so you could do the following

plugins_prod.yml:

```yaml
basic_config: &plugin_list
     plugin1: ...
     plugin2: ...
```

plugins_dev.yml:

```yaml
basic_config:
     <<: *plugin_list
     add_uri: ...
```

**Comment by Neirda24** [comment]
ok thanks @joelwurtz . But I was talking on different server environment not symfony ones. despite that I think your solution is good when integrated with a yaml parser (like symfony) but the library itself would not be standalone.

**Comment by joelwurtz** [comment]
Even if you have different server environment, you need to configure them differently, how do you proceed for that ?

**Comment by dbu** [comment]
> but the library itself would not be standalone.

the library has no yaml configuration. if you write PHP code to wire things up, you can check if you have a path defined, or an empty path, and then not put the plugin into the array of plugins.

**Comment by Neirda24** [comment]
Usually I like the idea of parameters. Changing predefined parameters to change the app targets. but never to change its way of working. it should be idempotent so one plugin activated on a srever should be activated on another. just the configuration of it might defer.

**Comment by Nyholm** [comment]
I will close this because it mentions a few solutions. 
There looks like there is also an agreement among maintainers not to allow `AddPath` to support an empty string.
