### ISSUE TITLE
spl_object_hash collisions

### ISSUE THREAD

**Issue by wvanderstel** [php-http/client-common#118]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 1.8.0 and higher

#### Behavior
The method "spl_object_hash" can issue the same hash for two different objects **if** one of the objects has been destroyed (i.e. garbage collector run).

This hash collision can cause a request to pass without actually adding the path.

See the notes for "spl_object_hash" in the PHP documentation: http://php.net/manual/en/function.spl-object-hash.php 

#### Steps to Reproduce
Send multiple requests with the same HTTP client.

#### Possible Solutions
1. Do not cache requests (as done in 1.70)
2. Do not use 'spl_object_hash' for hashing objects

**Comment by dbu** [comment]
this is being discussed in #113 - glad if you can have a look at the discussion (not the current code change) and give your input

**Comment by Nyholm** [comment]
This will be fixed in 2.x
