### ISSUE TITLE
[2.0] Inject PSR18 Client instead of Httplug when using Decoration

### ISSUE THREAD

**Issue by joelwurtz** [php-http/client-common#122]
So people not using our adapter / interface can still use this library

**Comment by dbu** [comment]
that would mean changing the typehints on our decorators, right? anything more?

**Comment by joelwurtz** [comment]
> that would mean changing the typehints on our decorators, right? anything more?

That and some `instanceof HttpClient` present in some parts of the code.

**Comment by dbu** [comment]
cool, then i am +:100: on this. want to do a pull request?

**Comment by joelwurtz** [comment]
Will try to do it soon

**Comment by dbu** [comment]
fixed in #135 

(@Nyholm seems that mentioning that in a comment is not enough to trigger github to autoclose the issue ;-) )
