### ISSUE TITLE
Retry Plugin should also retry responses with status 5xx

### ISSUE THREAD

**Issue by dbu** [php-http/client-common#126]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 2

#### Actual Behavior

We only retry if there is an exception thrown.

#### Expected Behavior

We should also retry when a response arrives but the status is indicating a server error.

#### Possible Solutions

- a) Have an exception decider and a response decider (and same for delay)
- b) Expand the decider and delay functions to also pass them the response. This would be a hard BC break

**Comment by dbu** [comment]
i think i prefer a) to avoid the BC break. also, there will never be both exception and response and the retry plugin knows in which part it is.

i suggest keeping the names for the exception decider and delay and adding a response_decider and response_error_delay that have request and response as argument, and no exception.

**Comment by joelwurtz** [comment]
Prefer a) also

But would like to change the name and deprecate older ones for consistency
