### ISSUE TITLE
Rename FlexibleHttpClient

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/client-common#16]
As per @dbu's concerns in one of the PRs.

His proposition is HttpSyncAsyncClient which sounds a little bit weird to me.

Any input?

**Comment by dbu** [comment]
i was not aware that the client was already merged and not added in that PR. given that, i can live with keeping the name. i just felt the name is not really telling what this is. "flexible" is a very broad term... 

if we find a great name to express that the client wraps any client and makes it work with both sync and async interface, we could rename this (with BC code of course) but just rename it to some other weird name is no improvement.

**Comment by sagikazarmark** [comment]
There was no release since the PR got merged, so we are free to change.

**Comment by joelwurtz** [comment]
UltimateHttpClient :trollface:

**Comment by sagikazarmark** [comment]
Closing this for now as no better ideas.
