### ISSUE TITLE
HttpMethodsClient not using  psr-17 factories

### ISSUE THREAD

**Issue by sunkan** [php-http/client-common#173]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | yes
| Version      | 2.0

Hi

Why dose `HttpMethodsClient` use `Http\Message\RequestFactory` instead of the psr-17 interfaces. 

At the moment the only why to use `HttpMethodsClient` is to write wrapper classes around the psr-17 implementation.

Are there any plans to fix this?
I can put together a pull request if  that's needed, but the problem is that this will be a bc break. So I don't know how you would like to solve this problem

**Comment by xabbuh** [comment]
Removing the type hint and then creating the request depending on the factory type should be possible, shouldn't it?

**Comment by GrahamCampbell** [comment]
This has been fixed now, and can be closed. I would have reffed this issue in my PR, had I seen it before!

// cc @dbu
