### ISSUE TITLE
Allow Symfony 5

### ISSUE THREAD

**Issue by garak** [php-http/client-common#174]
Symfony 5 is [about to be released](https://symfony.com/blog/symfony-5-0-curated-new-features), it would be nice to get support for it

**Comment by garak** [comment]
@dbu I guess it's not fair to close an issue until it's solved

**Comment by dbu** [comment]
@garak github closed that automatically when i merged #175

**Comment by garak** [comment]
Sorry I was mislead by the "Open" label here, then I realized it was unrelated. I deleted my original comment
