### ISSUE TITLE
HttpMethodsClient not working with PSR-17

### ISSUE THREAD

**Issue by jdecool** [php-http/client-common#201]
**Description**
The `HttpMethodsClient` constructor allows to get an `RequestFactory` or `RequestFactoryInterface` as second parameter.

Both declare the `createRequest` but don't have the same argument.

`RequestFactoryInterface::createRequest` only have two parameters `method` and `uri`.

The `HttpMethodsClient::send` method which is used to make the HTTP call have two other parameters. So when using a PSR-17 implementation, the code will not work as the body and/or headers won't be sent.

**How to reproduce**

```php
$http = new HttpMethodsClient(HttpClientDiscovery::find(), Psr17FactoryDiscovery::findRequestFactory());
$response = $http->get($uri, $headers);
```

Headers will not be sent.

**Comment by GrahamCampbell** [comment]
I cannot replicate this. Which particular client are you discovering. Maybe they have a bug?

**Comment by jdecool** [comment]
I use `guzzle6-adapter` as it doesn't provide a PSR-17 implementation, I use it with `nyholm/psr7`.

But beyond that, if we look at the interfaces definitions:

```php
namespace Http\Message;

interface RequestFactory
{
    public function createRequest($method, $uri, array $headers = [], $body = null, $protocolVersion = '1.1');
}
```

```php
namespace Psr\Http\Message;

interface RequestFactoryInterface
{
    public function createRequest(string $method, $uri): RequestInterface;
}
```

There is a problem.

Do you have an example with a working PSR-17 implementation ?

**Comment by GrahamCampbell** [comment]
`php-http/guzzle6-adapter:^2.0.1 http-interop/http-factory-guzzle:^1.0` should work correctly. You don't need two different psr7 implementations.

**Comment by GrahamCampbell** [comment]
That said, both should work. // cc @Nyholm

**Comment by GrahamCampbell** [comment]
NB You can also use Guzzle 7: `guzzlehttp/guzzle:^7.0.1 http-interop/http-factory-guzzle:^1.0`.

**Comment by jdecool** [comment]
Yeah it's work with your deps.

I think you need to update the library documentation. 
With the latest versions, adapters are not require anymore (`php-http/guzzle6-adapter` for exampe) ? 

I'm a bit annoyed by the code that depends on two interfaces that have different contracts.

**Comment by jdecool** [comment]
Not working.

I use those dependencies:

```json
"require": {
        "php": "^7.3",
        "ext-json": "*",
        "php-http/client-common": "^2.2",
        "php-http/client-implementation": "^1.0",
        "php-http/discovery": "^1.6",
        "php-http/httplug": "^2.0",
        "http-interop/http-factory-guzzle": "^1.0",
        "php-http/guzzle6-adapter": "^2.0"
},
```

With this code:

```php
$http = new Http\Client\Common\HttpMethodsClient(
    Http\Discovery\HttpClientDiscovery::find(),
    Http\Discovery\Psr17FactoryDiscovery::findRequestFactory(),
);

$response = $http->get('http://foo/bar', ['My-Header' => 'Value']);
```

A debug in `HttpMethodsClient::send`:

![image](https://user-images.githubusercontent.com/433926/87856453-976e9f80-c91f-11ea-8ddf-f46ea918b6e2.png)

And in it's implementation:

![image](https://user-images.githubusercontent.com/433926/87856472-ad7c6000-c91f-11ea-945a-89b1c374f213.png)

Headers are not set.

**Comment by jdecool** [comment]
I don't understand how the code could work as the two interface allows in the `HttpMethodsClient` doesn't have the same contract.

**Comment by GrahamCampbell** [comment]
>         "php-http/client-implementation": "^1.0",

You don't need this line, in fact you should not add it.

**Comment by GrahamCampbell** [comment]
> Headers are not set.

Let me take a look at this in more detail...

**Comment by GrahamCampbell** [comment]
I think you absolutely right, and the reason I hadn't seen this bug before is because I happened to be using something that was also a PHP-HTTP request factory, and not just a PSR one. There is definitely a bug here.

**Comment by GrahamCampbell** [comment]
I will prepare a PR to fix this. :)

**Comment by GrahamCampbell** [comment]
This is actually quite a disaster, because we also need a stream factory to be able to create the body!

**Comment by GrahamCampbell** [comment]
I think we can add it to the constructor as a 3rd param, and only complain about its absence at runtime if it was needed. We can also raise a deprecation error if it is omitted.

**Comment by GrahamCampbell** [comment]
@jdecool Please let me know what you think of https://github.com/php-http/client-common/pull/202.

**Comment by jdecool** [comment]
> Please let me know what you think of #202.

Look good to me
