### ISSUE TITLE
PhpDoc: missing attribute 'stream_factory'

### ISSUE THREAD

**Issue by Chris53897** [php-http/client-common#244]
https://github.com/php-http/client-common/blob/2.x/src/Plugin/RedirectPlugin.php#L116

I guess the correct one is this. (or FQCN)
@param array{'preserve_header'?: bool|string[], 'use_default_for_multiple'?: bool, 'strict'?: bool, 'stream_factory'?:StreamFactoryInterface} $config

**Comment by dbu** [comment]
oh right. yes your suggestion looks right. i think the tools that understand array shapes also understand `use`, so the short name is better to keep it readable.

**Comment by dbu** [comment]
fixed in #245
