### ISSUE TITLE
Tag 1.3.0?

### ISSUE THREAD

**Issue by Nyholm** [php-http/client-common#41]
Are we happy with the ClientPool? Are we confident to tag 1.3.0?

**Comment by joelwurtz** [comment]
Is it possible to add a experimental flag on ClientPool ? In fact i'm not still confident on the public api exposed and the way we can extends the Pool i would prefer to have something that can be broken on HttpClientPool but not quite sure on how to reflect that ?

**Comment by sagikazarmark** [comment]
I am happy with the current state.

@joelwurtz Do you think ClientPool is done and ready for release?

**Comment by sagikazarmark** [comment]
I see. Well, I would be happier if we could avoid releasing experimental stuff, but the HTTP Promise thing should be released as soon as possible. Is there a list of issues that we should still solve/discuss for the client pool?

Based on that we could decide whether we want to wait for the Pool clients to get more mature or just mark them as experimental and release the next version.

**Comment by joelwurtz** [comment]
or just mark all methods inside as `@internal` ?

**Comment by sagikazarmark** [comment]
That's okay from a logical point of view, but could still lead to code breaks which I would like to avoid. That said, we can make that call, but I would like to see the current state clearly.

**Comment by Nyholm** [comment]
> or just mark all methods inside as @internal ?

And the class. 

One could also release a version without the ClientPool.

**Comment by GrahamCampbell** [comment]
I'd say tag this thing. 👍

**Comment by acrobat** [comment]
Any news on an eta for the 1.3 release?

**Comment by sagikazarmark** [comment]
As far as I can see this is just about to happen.

**Comment by Nyholm** [comment]
Yes. We will tag 1.3.0 this weekend.
