### ISSUE TITLE
Use HttpClientNotFoundException for HttpClientRouter

### ISSUE THREAD

**Issue by joelwurtz** [php-http/client-common#44]
| Q | A |
| --- | --- |
| Bug? | yes (BC ?) |
| New Feature? | no |
#### Actual Behavior

Actually the HttpClientRouter use a RequestException which is not easily identifiable
#### Expected Behavior

Have an exception that pinpoint this specific use case (and we could profit from the exception added by ClientPool)

**Comment by dbu** [comment]
as long as that exception extends RequestException, this is no BC break and we can do it. seems reasonable to me.

**Comment by joelwurtz** [comment]
Actually HttpClientNotFoundException extends TransferException and not RequestException, and i think it's better as the exception have nothing to do with the request in the case of the HttpClientPool but since it's depend on the request for the HttpClientRouter maybe it's better to have another exception ?

`HttpClientNoMatchException` ?

**Comment by sagikazarmark** [comment]
Hm, not sure. I agree with the reasoning that this error does not really have any connection to sending the request. On the other hand, the request provides some context as it tells you FOR WHICH REQUEST there is no HTTP Client found.

**Comment by joelwurtz** [comment]
Totally agree (maybe i wasn't clear enough) but it make sense only for the HttpClientRouter, however the request has no influence on a HttpClientPool.

**Comment by sagikazarmark** [comment]
Okay, so the question here is whether we make the compromise and use the existing exception without the request context or create an entirely new one?

**Comment by joelwurtz** [comment]
yes

**Comment by dbu** [comment]
do we have something that looks at the request to decide which client to take? if so, the request can be relevant why we found no client. then we should create a new exception that extends the HttpClientNotFoundException and knows about the request.

**Comment by dbu** [comment]
i added this to the 2.0 milestone because i think we should decide on this as now we can also do a BC break if that is the best solution.
