### ISSUE TITLE
ContentLengthPlugin doesn't work with Diactoros

### ISSUE THREAD

**Issue by lunika** [php-http/client-common#55]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no

#### Actual Behavior

ContentLengthPlugin has a conflict when Diactoros is used. `MessageInterface::withHeader`  expects a string or a string collection for the `value` parameter and `Diactoros` checks if `value` respects this. ContentLengthPlugin inject an integer so an exception is thrown by Diactoros.

#### Expected Behavior

inject a string for the `value` paramter into `MessageInterface::withHeader` method

#### Steps to Reproduce

use the `ContentLengthPlugin` with `Diactoros`

#### Possible Solutions

cast `StreamInterface::getSize` return value in string [here](https://github.com/php-http/client-common/blob/master/src/Plugin/ContentLengthPlugin.php#L30) : 

```
$request = $request->withHeader('Content-Length', (string) $stream->getSize());
```

**Comment by sagikazarmark** [comment]
Would you mind opening a PR?

**Comment by lunika** [comment]
Yes I will do that today.
