### ISSUE TITLE
[RFC] Deprecate PluginClient debug_plugins option

### ISSUE THREAD

**Issue by fbourigault** [php-http/client-common#60]
I don't know the whole history of debug_plugins option (which was introduced in #22), but since this option is no longer used by HTTPlugBundle (https://github.com/php-http/HttplugBundle/pull/128), it could be deprecated and then removed in the next major version.

This will keep the PluginClient more simple.

**Comment by Nyholm** [comment]
Sure. Your ProfilePlugin has the same functionality. Let's deprecate it until someone says something else.

**Comment by fbourigault** [comment]
I'm not familiar with phpspec and I'm wondering how can I write a spec for the deprecation notice I will add?

**Comment by dbu** [comment]
wasn't there something about making a legacy annotation to that test? at least i think i have seen that with phpunit tests. maybe @sagikazarmark can help?

**Comment by sagikazarmark** [comment]
Not sure if we ever wrote tests for deprecation notices. I don't know about such annotation in PHPSpec.

**Comment by dbu** [comment]
then lets just deprecate i would say ;-)

**Comment by fbourigault** [comment]
Just for the knowledge, phpspec introduced the TriggerMatcher in it's [3.2 release](https://github.com/phpspec/phpspec/blob/master/CHANGES.md#320--2016-11-27).

We can't use it requires php 5.6+
