### ISSUE TITLE
Using Plugin Client hides the base HTTP Client being used

### ISSUE THREAD

**Issue by bretterer** [php-http/client-common#73]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | yes
| Version      | All

#### Actual Behavior

When using Plugin Client:

```
$this->httpClient = new PluginClient(
            $httpClient ?: HttpClientDiscovery::find(),
            [$authenticationPlugin, $redirectPlugin]
        );
```
this prevents me from being able to attach response objects when using the Mock Client.

```
$this->httpClient->addResponse($response);
```

#### Expected Behavior

I would expect to have access to the underlying http client so I can attach responses when using the Mock Client for testing.

#### Steps to Reproduce

See Above.

#### Possible Solutions

Add a method to PluginClient

```
public function getClient()
{
    return $this->client;
}

ping @Nyholm

**Comment by bretterer** [comment]
A re-organization of my test helps with this, but I think it should still provide a way to get the underlying HttpClient from the PluginClient instance.

**Comment by sagikazarmark** [comment]
I think it's a common practice to expose mocked objects within tests as separate parameters and not retrieve it from the subject.

So I am against this change.

That said, we might just do it in connection with another feature, but it would still be better to access the mock client in your tests differently.

**Comment by fbourigault** [comment]
I'm also against this change. The main issue is about breaking encapsulation which is bad here.
As Mark said, in your tests, while building the PluginClient, you must not use the discovery and provide the underlying HttpClient yourself and keep a reference to it somewhere. By doing so, you will be able to attach responses.

Can we close this issue?

**Comment by sagikazarmark** [comment]
Thanks for the contribution, but this is not something we would like to add at this time.
