### ISSUE TITLE
HttpClientPool

### ISSUE THREAD

**Issue by joelwurtz** [php-http/client-common#8]
Having an HttpClient / HttpAsyncClient, that accept a list of differents clients and balance requests over them, should also remove a client from the list if one of the request fail.

You can see something like this here : https://github.com/elastic/elasticsearch-php/tree/master/src/Elasticsearch/ConnectionPool

**Comment by sagikazarmark** [comment]
I can see the usecase in elastic, but what would be on pure HTTP level?

**Comment by joelwurtz** [comment]
I think there can be other usage for cluster related thing and also for api having fallback mirrors (like package manager or other stuff)

**Comment by sagikazarmark** [comment]
Hm, makes sense. And client common would be the perfect fit I guess.

**Comment by joelwurtz** [comment]
Maybe we need to separate the load balance of request and the fallback feature into 2 differents clients ?

**Comment by joelwurtz** [comment]
Or having some sort of parameters for the load balance thing

**Comment by sagikazarmark** [comment]
> Maybe we need to separate the load balance of request and the fallback feature into 2 differents clients ?

If you want to support more than one Clients and you want both feature at the same time, I am not sure you can separate them.

**Comment by joelwurtz** [comment]
Yeah the parameter way is better for this :)
