### ISSUE TITLE
Content-type plugin

### ISSUE THREAD

**Issue by kpn13** [php-http/client-common#82]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 

Hi,

Do you think a plugin which will automatically set the content-type header based on what it can find in the body request would be a good idea ? I can do a pull request on it if you approved this idea.

Thanks in advance.

**Comment by joelwurtz** [comment]
Hey, it can be nice yes, wondering how you will do it as from my experience it's far from being easy :)

**Comment by kpn13** [comment]
Hum I don't say it will be easy :). Well, if I start by detect json content and xml content it is I think relatively simple and will respond to major needs, no ?

**Comment by joelwurtz** [comment]
Yes would be a good start, but implementation will matters, as i will certainly be against a too complex one that is hard to maintain.
