### ISSUE TITLE
fix styleci build

### ISSUE THREAD

**Issue by dbu** [php-http/client-common#89]
we currently get styleci failures on master because it wants yoda for everything. we can either change to code to that, or we can add configuration to the styleci file to skip the yoda check.

i vote to change the code. for variables its the right thing imo, and for method calls it does not matter and we can't disable that separately.

**Comment by sagikazarmark** [comment]
I would be happier if we could apply yoda only to variables, but to be honest I really don't care that much. So I abstain from voting for/against it.

Just placing this link here so it doesn't get lost: https://dev.to/greg0ire/why-using-yoda-conditions-you-should-probably-not

**Comment by dbu** [comment]
i read that post against yoda but i don't agree with it. even if you have perfect test coverage, spotting the odd mistake can waste time, and i don't see the problem with ordering. at least this is a clear rule and will be consistent in the code base.

**Comment by sagikazarmark** [comment]
Well, as said I don't think it's worthy for an argument. It's like tabs and spaces. Decide on one thing and stick to it, don't mind which one.

If the others have no opinion on the matter, just go ahead and change. :)

**Comment by dbu** [comment]
lets wait a bit. if others don't like yoda-style i have no problem disabling that rule, its indeed tabs vs spaces :-D as long as styleci gets green again.

**Comment by sagikazarmark** [comment]
> lets wait a bit.

Yeah, I meant that.

**Comment by Nyholm** [comment]
I have no real opinion. We use Symfony code styles already (with the exception from the Interface suffix). 
@dbu If you think there is some value in using yoda then please do. Just wait "a bit" (maximun a day) for feedback.

**Comment by fbourigault** [comment]
The only opinion I have is to have consistent coding style across the entire organization.

**Comment by joelwurtz** [comment]
Consistency on this level is a completly no care, we should just put yoda on null, and let the developer decide. But if we want to force a value, i would prefer have it to false.

**Comment by kelunik** [comment]
Adding this from https://github.com/php-http/artax-adapter/pull/12

> I personally really hate Yoda conditions. They don't fit in the natural reading flow of humans. Do we really need that rule?

**Comment by dbu** [comment]
i got used to it personally. the more "general" reasoning is that symfony does follow yoda, and we said at some point we want to follow symfony to avoid discussions.
