### ISSUE TITLE
Use less strict promises

### ISSUE THREAD

**Issue by popy-dev** [php-http/client-common#95]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

HttpAsyncClient actually returns an Http***Promise, which enforces its result type to be an HTTP Response. That's all nice and dandy, but it actually prevents to transform the result in anything else.

I hited this wall while implemening a REST Client, with a middleware chain (quite like the plugin chain), when the final Middleware failed to transform the HTTP Response into my internal REST Response.

(I know I could also code/find a proper Promise implementation and plug it after the Http****Promise, but doesn't it would defeat the purpose of Promises ? Or am I understanding it wrong ?)

**Comment by sagikazarmark** [comment]
Hi @popy-dev 

Our current philosophy is that HTTP pipeline is for HTTP stuff. Transformed, non-HTTP internal objects shouldn't cross it's boundaries.

There were a number of (both technical and architectural) reasons why we decided to introduce this limitations, some of which are detailed in the documentation.

We are awaiting (pun intended) some changes in the PHP+async world which might make things simpler and allow us to introduce some changes on this front, but for now this won't change in the the near future.

**Comment by dbu** [comment]
your architecture could be:
```
ApiClient::getProduct(id): ProductPromise
{
    request = build request to get id
    httpPromise = httpClient->sendAsyncRequest(request)
    productPromise = wrap promise to transform response data into domain object

    return productPromise
}
```

with this, you have no leaking of http into your domain and clear boundaries.
