### ISSUE TITLE
Add a new plugin to the PluginClient

### ISSUE THREAD

**Issue by Taluu** [php-http/client-common#96]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 1.7.0

#### Actual Behavior
Once your `PluginClient` has been initialized, you can't add new plugins to it

#### Expected Behavior
Being able to add some new plugins on the fly. I'm currently registering it in a Behat container, so I registered a few plugins on the construct https://github.com/Taluu/Behapi/blob/master/src/Container.php#L85.

But I would like to be able to give the possibility for the users to add some new plugins (such as the auth plugin or a random listener) so that they can do stuff on their own.

#### Possible Solutions
Add a `addPlugin` or something to the `PluginClient`

**Comment by Taluu** [comment]
I could try to use something like #40 though in order to go around this "problem" (Because I don't really want to rewrite the plugin client just to add a `addPlugin` method)

**Comment by joelwurtz** [comment]
This is somehow intended, because adding a plugin can change the behavior of your http client (like the error plugin or even the decode one). So it has a high chance of side effect and WTF errors in many situation.

So yes please use the plugin client builder in order to achieve that.

**Comment by joelwurtz** [comment]
In fact, we may accept having an addPlugin method if it's immutable (return a new PluginClient instance)

**Comment by Taluu** [comment]
The problem being that the builder was not merged, the factory was merged instead. And in the factory, you have to specify all the plugins in the factory method.

So it's not possible ATM unless you make your own builder, which I intend to do (Even though I think I shouldn't have to do it, and it should be handled by this repo)

**Comment by Taluu** [comment]
Having it immutable is a no go too, because I'm injecting this client through a DI, and each services depending on that client *may* have to add some plugins. So I need to modify the instance, and not have another one.

**Comment by joelwurtz** [comment]
In fact having both a builder and a factory can make sense as they have different approach, and i totally understand your use case which and it might be useful for other libraries, so you can propose a builder here.

**Comment by Taluu** [comment]
After another glance at the pluginclient, I don't think having a `addPlugin` modifying the same object can have side-effects, as in the constructor, the plugin list is left as is. It's only in the sendRequest (and its async counterpart) that the chain is being built, and at this point it is safe to assume that it won't move.

Maybe adding a sort of "freeze flag" on the first `sendRequest` (or the async one) would do the trick ?

ofc, the builder is the best solution IMO.

**Comment by dbu** [comment]
we do have the plugin build, so can we close this issue or is there something left open?

**Comment by Taluu** [comment]
AFAIC, there is no such builder ? As said earlier, the factory isn't what I was looking for (but the closed builder was, but was not merged...,). I built my own builder, but I'm still convinced it should be done in this repository....

Unless I missed something ?

**Comment by dbu** [comment]
i was looking at https://github.com/Taluu/Behapi/pull/44 but did not realize that its in a different repository :man_facepalming: 

do you want to do a pull request to add such a builder, then?

**Comment by Nyholm** [comment]
What is the scenario for adding a new plugin? 

You said you use the plugin client as a service in you DIC. Services should be immutable so I dont understand why you ever would like to modify the behavior of a HTTP client in runtime

**Comment by Taluu** [comment]
The service I'm injecting is the builder actually. I need to do this in my Behat extension so that I can add an auth plugin to the http client. The thing is, there are as many auths (and plugins thus...), and covering them all through configs of sorts would be IMO unefficient.

Thus why I made the plugin client builder. You can see a use-case here : https://gist.github.com/Taluu/ea4ea97391b5dd7fa4d762d536b83e52. I am using another context for the auth part, and I need to inject an auth plugin in this particular context.

**Comment by Nyholm** [comment]
Okey. I understand. Thank you. 

I do something similar here: https://github.com/KnpLabs/php-github-api/blob/2.10.1/lib/Github/Client.php#L314-L331

It seams like both you and I have created solution that work with the current implementation. (Where we are both immutable and final)

What code change do you suggest? And why would that be an improvement?

**Comment by Taluu** [comment]
If we would keep the plugin's client immutability (not a wrong idea IMO), adding a plugin client builder as you tried to do in #40 would be a good step I think.

Yes, this builder would not be "immutable", but as it's a builder, isn't it the purpose of such objects ? We could mark it as final though.

**Comment by Nyholm** [comment]
Okey. 
Since I have duplicated the logic in the github client to many other API clients, one could argue that there is a good need for a builder. 

I would be happy to review a PR for that. 

That PR is not blocking for 2.0.

**Comment by dbu** [comment]
this will be solved with the builder in #158
